import type { AnalysisData, Conversation, Product } from "./types";

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-iphone",
    title: "iPhone 15 Pro Max 比价分析",
    updatedAt: Date.now() - 3_600_000,
    status: "completed",
    progress: 100,
    unread: false,
  },
  {
    id: "conv-macbook",
    title: "MacBook Air M2 比价",
    updatedAt: Date.now() - 7_200_000,
    status: "idle",
    progress: 0,
    unread: false,
  },
  {
    id: "conv-switch",
    title: "Switch OLED 价格监控",
    updatedAt: Date.now() - 86_400_000,
    status: "completed",
    progress: 100,
    unread: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    title: "iPhone 15 Pro Max 256G 国行",
    price: 7800,
    condition: "99新",
    platform: "闲鱼",
    location: "上海",
    favorites: 23,
    views: 412,
    aiScore: 94,
    riskScore: 12,
    url: "https://example.com/p1",
  },
  {
    id: "p2",
    title: "iPhone 15 Pro Max 256G 深空黑",
    price: 7650,
    condition: "99新",
    platform: "闲鱼",
    location: "深圳",
    favorites: 18,
    views: 356,
    aiScore: 91,
    riskScore: 15,
    url: "https://example.com/p2",
  },
  {
    id: "p3",
    title: "iPhone 15 Pro Max 256G 全套",
    price: 6680,
    condition: "95新",
    platform: "闲鱼",
    location: "北京",
    favorites: 31,
    views: 520,
    aiScore: 88,
    riskScore: 22,
    url: "https://example.com/p3",
  },
  {
    id: "p4",
    title: "iPhone 15 Pro Max 256G 原色",
    price: 9150,
    condition: "全新",
    platform: "闲鱼",
    location: "杭州",
    favorites: 9,
    views: 180,
    aiScore: 76,
    riskScore: 8,
    url: "https://example.com/p4",
  },
  {
    id: "p5",
    title: "iPhone 15 Pro Max 256G",
    price: 5420,
    condition: "90新",
    platform: "闲鱼",
    location: "广州",
    favorites: 12,
    views: 290,
    aiScore: 72,
    riskScore: 35,
    url: "https://example.com/p5",
  },
  {
    id: "p6",
    title: "iPhone 15 Pro Max 256G 电池健康96",
    price: 7280,
    condition: "99新",
    platform: "闲鱼",
    location: "成都",
    favorites: 27,
    views: 445,
    aiScore: 92,
    riskScore: 14,
    url: "https://example.com/p6",
  },
];

export const MOCK_ANALYSIS: AnalysisData = {
  summary: [
    "99新商品数量最多，价格集中在 ¥7,200 - ¥8,200",
    "95新具有较高性价比，适合预算有限用户",
    "全新商品存在明显溢价，平均高出 15%",
    "90新以下价格较低但风险更高，需仔细验机",
  ],
  recommendedRange: { min: 7200, max: 8200 },
  priceBuckets: [
    { label: "全新未拆封", min: 8800, max: 9500, average: 9150, count: 28 },
    { label: "99新", min: 7200, max: 8200, average: 7650, count: 156 },
    { label: "95新", min: 6200, max: 7200, average: 6650, count: 98 },
    { label: "90新及以下", min: 4800, max: 6200, average: 5350, count: 46 },
  ],
  distribution: [
    { range: "4K-5K", count: 12 },
    { range: "5K-6K", count: 34 },
    { range: "6K-7K", count: 78 },
    { range: "7K-8K", count: 142 },
    { range: "8K-9K", count: 48 },
    { range: "9K+", count: 14 },
  ],
  recommendation: {
    productId: "p1",
    reasons: [
      "价格低于同类 99新 商品平均价格",
      "成色较好，配件齐全",
      "卖家历史交易情况正常",
      "综合性价比较高",
    ],
    priceAdvantage: "低于均价约 ¥150",
    condition: "99新",
    sellerTrust: "良好",
    risk: "低",
  },
};
