// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarNodeModel {
    pub node: String,
    pub account_id: Option<String>,
    pub base_url: String,
    pub api_key: String,
    pub model: String,
    pub provider_type: Option<String>,
}
