// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunStatusRequest {
    pub run_id: String,
    pub since_index: Option<i64>,
    pub trace_id: Option<String>,
}
