// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::AgentSidecarRunStep;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunStatusResponse {
    pub ok: bool,
    pub run_id: String,
    pub state: String,
    pub current_node: Option<String>,
    pub completed_nodes: Option<Vec<String>>,
    pub steps: Option<Vec<AgentSidecarRunStep>>,
    pub reply: Option<String>,
    pub error: Option<String>,
    pub error_kind: Option<String>,
    pub failed_node: Option<String>,
    pub message: Option<String>,
}
