// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunStartResponse {
    pub ok: bool,
    pub run_id: String,
    pub state: String,
    pub message: Option<String>,
}
