// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::AgentSidecarNodeModel;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunStartRequest {
    pub run_id: Option<String>,
    pub user: String,
    pub system: Option<String>,
    pub kind: Option<String>,
    pub node_models: Option<Vec<AgentSidecarNodeModel>>,
    pub default_base_url: Option<String>,
    pub default_api_key: Option<String>,
    pub default_model: Option<String>,
    pub resume_from_run_id: Option<String>,
    pub resume_state_json: Option<String>,
    pub resume_node: Option<String>,
    pub trace_id: Option<String>,
}
