// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::AgentSidecarNodeModel;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunControlRequest {
    pub run_id: String,
    pub action: String,
    pub node: Option<String>,
    pub node_model: Option<AgentSidecarNodeModel>,
    pub trace_id: Option<String>,
}
