// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunCancelRequest {
    pub run_id: String,
    pub trace_id: Option<String>,
}
