// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSidecarRunStep {
    pub node: String,
    pub index: i64,
    pub status: String,
    pub label: Option<String>,
    pub detail: Option<String>,
    pub error_kind: Option<String>,
    pub account_id: Option<String>,
    pub model: Option<String>,
    pub content: Option<String>,
    pub state_before_json: Option<String>,
}
