// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::AiGraphNodeAccount;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiGraphModels {
    pub node_accounts: Option<Vec<AiGraphNodeAccount>>,
    pub failover_account_ids: Option<Vec<String>>,
    pub failover_enabled: Option<bool>,
}
