// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::{AiAccount, AiGraphModels, AiProvider};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiIpcConfigRequest {
    pub providers: Vec<AiProvider>,
    pub accounts: Vec<AiAccount>,
    pub graph_models: Option<AiGraphModels>,
}
