// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelSidecarSearchResponse {
    pub ok: bool,
    pub status: String,
    pub keyword: String,
    pub total: i64,
    pub total_before_filter: Option<i64>,
    pub offers: Vec<String>,
    pub final_url: Option<String>,
    pub detail: Option<String>,
    pub trace_id: Option<String>,
}
