// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::{
    ChannelAccount, ChannelConversation, ChannelMessage, ChannelSettings,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelIpcStateResponse {
    pub accounts: Vec<ChannelAccount>,
    pub conversations: Vec<ChannelConversation>,
    pub messages: Vec<ChannelMessage>,
    pub settings: ChannelSettings,
}
