// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelIpcOpenSiteRequest {
    pub account_id: String,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}
