// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelIpcSendResponse {
    pub ok: bool,
    pub message_id: String,
    pub detail: Option<String>,
}
