// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelAli1688SearchOffer {
    #[serde(rename = "offerId")]
    pub offer_id: String,
    pub title: String,
    pub price: Option<String>,
    pub supplier: Option<String>,
    pub location: Option<String>,
    pub tags: Option<Vec<String>>,
    pub turnover: Option<String>,
    #[serde(rename = "isP4P")]
    pub is_p4_p: Option<bool>,
    pub url: String,
    pub image: Option<String>,
}
