// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelXianyuSearchItem {
    #[serde(rename = "itemId")]
    pub item_id: String,
    pub title: String,
    pub url: String,
    pub image: Option<String>,
    pub price: Option<String>,
    pub location: Option<String>,
    pub seller: Option<String>,
    #[serde(rename = "wantCount")]
    pub want_count: Option<String>,
    #[serde(rename = "publishedAt")]
    pub published_at: Option<String>,
    pub tags: Option<Vec<String>>,
}
