// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::{ChannelAccount, ChannelSettings};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelIpcStateRequest {
    pub accounts: Vec<ChannelAccount>,
    pub settings: ChannelSettings,
}
