// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelSidecarLoginProbeResponse {
    pub ok: bool,
    pub online: bool,
    pub status: String,
    pub final_url: Option<String>,
    pub detail: Option<String>,
    pub trace_id: Option<String>,
}
