// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::ChannelCookie;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelSidecarCookieRenewResponse {
    pub ok: bool,
    pub status: String,
    pub cookies: Option<Vec<ChannelCookie>>,
    pub detail: Option<String>,
    pub trace_id: Option<String>,
}
