// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::ChannelMessage;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelEventMessage {
    pub account_id: String,
    pub message: ChannelMessage,
    pub suggestion: Option<String>,
}
