// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelSidecarQrCancelResponse {
    pub ok: bool,
    pub detail: Option<String>,
    pub trace_id: Option<String>,
}
