// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::ChannelCookie;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelSidecarLoginProbeRequest {
    pub account_id: String,
    pub cookies: Vec<ChannelCookie>,
    pub headed: Option<bool>,
    pub platform: Option<String>,
    pub trace_id: Option<String>,
}
