// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::PluginItem;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginIpcInstallResponse {
    pub item: PluginItem,
}
