// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginEventProgress {
    pub plugin_id: String,
    pub received_bytes: i64,
    pub total_bytes: i64,
    pub file_name: String,
}
