// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::contracts::PluginItem;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginIpcListResponse {
    pub items: Vec<PluginItem>,
}
