// Auto-generated by sync_contracts.py — do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeLogEntry {
    pub schema_version: String,
    pub timestamp: String,
    pub level: String,
    pub source: String,
    pub logger: String,
    pub message: String,
    pub event: Option<String>,
    pub feature: Option<String>,
    pub trace_id: Option<String>,
    pub task_id: Option<String>,
    pub tenant_id: Option<String>,
    pub attributes: Option<String>,
    pub exception: Option<String>,
}
