//! 闲鱼 IPC 链步骤 — 启用时追加命令并交给下一站。

#[cfg(platform_xianyu)]
#[macro_export]
macro_rules! platform_ipc_step_xianyu {
    ($($prior:tt)*) => {
        $crate::platform_ipc_link_after_xianyu!(
            $($prior)*
            account_connect,
            account_cookie_renew,
            account_disconnect,
            account_connection_state,
            order_list,
            order_get,
            order_update_status,
            order_update_delivery,
            order_create,
            order_delete,
            item_list,
            item_get,
            item_update,
            item_sync,
            item_detail_fetch,
            risk_log_list,
            risk_log_today_rate,
            risk_log_clear,
            risk_log_clear_processing,
            risk_config_get,
            risk_config_set,
            user_setting_get,
            user_setting_set,
            dashboard_stats,
            channel_fetch_history,
            channel_product_headinfo,
            channel_qr_start,
            channel_qr_check,
            channel_qr_cancel,
            xianyu_search,
            monitor_task_list,
            monitor_task_save,
            monitor_task_delete,
            monitor_task_pause_schedule,
            monitor_task_resume_schedule,
            monitor_task_run,
            monitor_result_list,
            monitor_run_list,
            monitor_run_get,
            monitor_stats,
            monitor_generate_keywords,
        )
    };
}
