#!/usr/bin/env python3
"""Sync contracts to codegen output directories (incremental: add / update / delete)."""

from __future__ import annotations

import argparse
import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path

from _common import CONTRACTS, ROOT, delete_if_exists, setup_logging, write_text_if_changed

TS_OUT = ROOT / "packages" / "contracts" / "src" / "generated"
PY_OUT = ROOT / "python" / "contracts" / "generated"
# Rust 端生成物已随 4c292a6 迁入 src-tauri；crates/common 为历史遗留，勿再写入。
RS_OUT = ROOT / "apps" / "desktop" / "src-tauri" / "src" / "contracts" / "contracts"

TYPE_MAP_TS = {
    "string": "string",
    "boolean": "boolean",
    "integer": "number",
    "number": "number",
}
TYPE_MAP_RS = {
    "string": "String",
    "boolean": "bool",
    "integer": "i64",
    "number": "f64",
}
TYPE_MAP_PY = {
    "string": "str",
    "boolean": "bool",
    "integer": "int",
    "number": "float",
}


@dataclass
class SyncStats:
    added: int = 0
    updated: int = 0
    deleted: int = 0
    unchanged: int = 0

    @property
    def changed(self) -> int:
        return self.added + self.updated + self.deleted


def _schema_names(rel: Path) -> tuple[str, str]:
    parts = list(rel.parts[:-1])
    stem = rel.name.removesuffix(".schema.json")
    if "." in stem:
        name_part, direction = stem.rsplit(".", 1)
        parts.extend([name_part, direction])
    else:
        parts.append(stem)
    pascal = "".join(
        "".join(seg[:1].upper() + seg[1:] for seg in part.split("_") if seg) for part in parts
    )
    snake = "_".join(parts)
    return pascal, snake


def _load_schema(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve_ref(ref: str, current_rel: Path, schema_root: Path) -> tuple[str, str]:
    if ref.startswith("#/"):
        raise ValueError(f"JSON-pointer refs not supported: {ref}")
    current_dir = (schema_root / current_rel).parent
    target = (current_dir / ref).resolve()
    try:
        rel = target.relative_to(schema_root.resolve())
    except ValueError as error:
        raise ValueError(f"ref outside schema root: {ref}") from error
    return _schema_names(rel)


def _collect_refs(
    spec: dict,
    current_rel: Path,
    schema_root: Path,
) -> list[tuple[str, str]]:
    refs: list[tuple[str, str]] = []
    if "$ref" in spec:
        refs.append(_resolve_ref(spec["$ref"], current_rel, schema_root))
    if spec.get("type") == "array":
        refs.extend(_collect_refs(spec.get("items", {}), current_rel, schema_root))
    return refs


def _prop_type_ts(spec: dict, current_rel: Path, schema_root: Path) -> str:
    if "$ref" in spec:
        return _resolve_ref(spec["$ref"], current_rel, schema_root)[0]
    stype = spec.get("type", "string")
    if stype == "array":
        items = spec.get("items", {})
        return f"{_prop_type_ts(items, current_rel, schema_root)}[]"
    return TYPE_MAP_TS.get(stype, "unknown")


def _prop_type_rs(spec: dict, current_rel: Path, schema_root: Path) -> str:
    if "$ref" in spec:
        return _resolve_ref(spec["$ref"], current_rel, schema_root)[0]
    stype = spec.get("type", "string")
    if stype == "array":
        items = spec.get("items", {})
        return f"Vec<{_prop_type_rs(items, current_rel, schema_root)}>"
    return TYPE_MAP_RS.get(stype, "String")


def _prop_type_py(spec: dict, current_rel: Path, schema_root: Path) -> str:
    if "$ref" in spec:
        return _resolve_ref(spec["$ref"], current_rel, schema_root)[0]
    stype = spec.get("type", "string")
    if stype == "array":
        items = spec.get("items", {})
        return f"list[{_prop_type_py(items, current_rel, schema_root)}]"
    return TYPE_MAP_PY.get(stype, "str")


def _schema_refs(schema: dict, rel: Path, schema_root: Path) -> list[tuple[str, str]]:
    refs: list[tuple[str, str]] = []
    for spec in schema.get("properties", {}).values():
        refs.extend(_collect_refs(spec, rel, schema_root))
    return sorted(set(refs))


def _emit_ts(name: str, schema: dict, rel: Path, schema_root: Path) -> str:
    required = set(schema.get("required", []))
    props = schema.get("properties", {})
    lines = ["// Auto-generated by sync_contracts.py — do not edit.", ""]
    for pascal, snake in _schema_refs(schema, rel, schema_root):
        lines.append(f'import type {{ {pascal} }} from "./{snake}";')
    if len(lines) > 2:
        lines.append("")
    lines.append(f"export interface {name} {{")
    for prop, spec in props.items():
        ts_type = _prop_type_ts(spec, rel, schema_root)
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _rs_field_name(prop: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", prop).lower()


def _emit_rs(name: str, schema: dict, rel: Path, schema_root: Path) -> str:
    required = set(schema.get("required", []))
    props = schema.get("properties", {})
    refs = _schema_refs(schema, rel, schema_root)
    lines = [
        "// Auto-generated by sync_contracts.py — do not edit.",
        "",
    ]
    # rustfmt reorder_imports 排序：crate 内部引用先于外部 crate。
    # 生成物位于 `src/contracts/contracts`（模块 `crate::contracts::contracts`），
    # 跨引用必须带 `contracts::` 前缀。
    if len(refs) == 1:
        lines.append(f"use crate::contracts::contracts::{refs[0][0]};")
    elif len(refs) > 1:
        joined = ", ".join(pascal for pascal, _ in refs)
        lines.append(f"use crate::contracts::contracts::{{{joined}}};")
    lines.append("use serde::{Deserialize, Serialize};")
    lines.append("")
    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append(f"pub struct {name} {{")
    for prop, spec in props.items():
        rs_type = _prop_type_rs(spec, rel, schema_root)
        if prop not in required:
            rs_type = f"Option<{rs_type}>"
        field = _rs_field_name(prop)
        if field != prop:
            lines.append(f'    #[serde(rename = "{prop}")]')
        lines.append(f"    pub {field}: {rs_type},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _emit_py(name: str, schema: dict, rel: Path, schema_root: Path) -> str:
    required = set(schema.get("required", []))
    props = schema.get("properties", {})
    lines = [
        '"""Auto-generated from contracts/schema."""',
        "",
        "from typing import TypedDict",
    ]
    for pascal, snake in _schema_refs(schema, rel, schema_root):
        lines.append(f"from .{snake} import {pascal}")
    lines.append("")
    lines.append("")
    if required == set(props):
        lines.append(f"class {name}(TypedDict):")
    else:
        lines.append(f"class {name}(TypedDict, total=False):")
    if not props:
        lines.append("    pass")
    else:
        for prop, spec in props.items():
            py_type = _prop_type_py(spec, rel, schema_root)
            lines.append(f"    {prop}: {py_type}")
    return "\n".join(lines) + "\n"


def _track_write(
    path: Path,
    content: str,
    *,
    dry_run: bool,
    stats: SyncStats,
    quiet: bool,
) -> None:
    existed = path.exists()
    if write_text_if_changed(path, content, dry_run=dry_run):
        action = "updated" if existed else "added"
        if action == "updated":
            stats.updated += 1
        else:
            stats.added += 1
        if not quiet:
            logging.info("%s %s", action, path.relative_to(ROOT))
    else:
        stats.unchanged += 1


def _cleanup_stale(
    out_dir: Path,
    expected_stems: set[str],
    extension: str,
    *,
    skip: set[str],
    dry_run: bool,
    stats: SyncStats,
    quiet: bool,
) -> None:
    if not out_dir.exists():
        return
    for path in sorted(out_dir.glob(f"*{extension}")):
        if path.name in skip or path.stem in expected_stems:
            continue
        if delete_if_exists(path, dry_run=dry_run):
            stats.deleted += 1
            if not quiet:
                logging.info("deleted %s", path.relative_to(ROOT))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="show actions only")
    parser.add_argument("--quiet", action="store_true", help="only log summary")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()
    setup_logging(args.verbose)
    quiet = args.quiet and not args.verbose

    schema_root = CONTRACTS / "schema" / "v1"
    if not schema_root.exists():
        logging.warning("no schemas at %s", schema_root)
        return 0

    schemas = sorted(schema_root.rglob("*.schema.json"))
    stats = SyncStats()
    expected_stems: set[str] = set()
    ts_exports: list[str] = []
    py_exports: list[str] = []
    rs_exports: list[str] = []

    for path in schemas:
        rel = path.relative_to(schema_root)
        pascal, snake = _schema_names(rel)
        expected_stems.add(snake)
        schema = _load_schema(path)

        ts_file = TS_OUT / f"{snake}.ts"
        py_file = PY_OUT / f"{snake}.py"
        rs_file = RS_OUT / f"{snake}.rs"

        _track_write(
            ts_file,
            _emit_ts(pascal, schema, rel, schema_root),
            dry_run=args.dry_run,
            stats=stats,
            quiet=quiet,
        )
        _track_write(
            py_file,
            _emit_py(pascal, schema, rel, schema_root),
            dry_run=args.dry_run,
            stats=stats,
            quiet=quiet,
        )
        _track_write(
            rs_file,
            _emit_rs(pascal, schema, rel, schema_root),
            dry_run=args.dry_run,
            stats=stats,
            quiet=quiet,
        )

        ts_exports.append(f'export type {{ {pascal} }} from "./{snake}";')
        py_exports.append(f"from .{snake} import {pascal}")
        rs_exports.append(f"pub mod {snake};")
        rs_exports.append(f"pub use {snake}::{pascal};")

    _cleanup_stale(
        TS_OUT,
        expected_stems,
        ".ts",
        skip={"index.ts"},
        dry_run=args.dry_run,
        stats=stats,
        quiet=quiet,
    )
    _cleanup_stale(
        PY_OUT,
        expected_stems,
        ".py",
        skip={"__init__.py"},
        dry_run=args.dry_run,
        stats=stats,
        quiet=quiet,
    )
    _cleanup_stale(
        RS_OUT,
        expected_stems,
        ".rs",
        skip={"mod.rs"},
        dry_run=args.dry_run,
        stats=stats,
        quiet=quiet,
    )

    ts_index = (
        "// Auto-generated by sync_contracts.py — do not edit.\n\n" + "\n".join(ts_exports) + "\n"
    )
    py_all = []
    for line in py_exports:
        match = re.search(r"import (\w+)", line)
        if match:
            py_all.append(f'    "{match.group(1)}",')

    py_index = (
        '"""Auto-generated contract index."""\n\n'
        + "\n".join(py_exports)
        + "\n\n__all__ = [\n"
        + "\n".join(py_all)
        + "\n]\n"
    )
    rs_index = (
        "// Auto-generated by sync_contracts.py — do not edit.\n\n" + "\n".join(rs_exports) + "\n"
    )

    _track_write(TS_OUT / "index.ts", ts_index, dry_run=args.dry_run, stats=stats, quiet=quiet)
    _track_write(PY_OUT / "__init__.py", py_index, dry_run=args.dry_run, stats=stats, quiet=quiet)
    _track_write(RS_OUT / "mod.rs", rs_index, dry_run=args.dry_run, stats=stats, quiet=quiet)

    if stats.changed == 0:
        logging.info("contracts unchanged (%d schemas)", len(schemas))
    else:
        logging.info(
            "contracts synced (%d schemas): +%d ~%d -%d (%d unchanged)",
            len(schemas),
            stats.added,
            stats.updated,
            stats.deleted,
            stats.unchanged,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
