# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — freeze DingDa Python sidecar for Tauri externalBin."""

from pathlib import Path

block_cipher = None
root = Path(SPECPATH)

a = Analysis(
    [str(root / "sidecar" / "main.py")],
    pathex=[str(root)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "crawlers",
        "crawlers.factory",
        "crawlers.channel",
        "crawlers.core.login.helpers",
        "crawlers.core.login.session",
        "crawlers.core.login.qrcode",
        "crawlers.core.browser.base",
        "crawlers.core.platform_config",
        "crawlers.core.playwright_common",
        "crawlers.core.camoufox",
        "crawlers.core.logging",
        "crawlers.xianyu.channel",
        "crawlers.xianyu.browser",
        "crawlers.xianyu.login.qrcode",
        "crawlers.xianyu.login.cookie_renew",
        "crawlers.xianyu.login.slider",
        "crawlers.xianyu.search",
        "crawlers.xianyu.search.fetch",
        "crawlers.xianyu.search.mtop",
        "crawlers.alibaba.channel",
        "crawlers.alibaba.browser",
        "crawlers.alibaba.browser.session",
        "crawlers.alibaba.login",
        "crawlers.alibaba.login.qrcode",
        "crawlers.alibaba.login.probe",
        "crawlers.alibaba.search",
        "crawlers.alibaba.search.fetch",
        "crawlers.alibaba.search.mtop",
        "sidecar.handlers.channel.qr",
        "sidecar.handlers.channel.cookie_renew",
        "sidecar.handlers.channel.search",
        "sidecar.handlers.channel.login_probe",
        "sidecar.main",
        "sidecar.server",
        "sidecar.routes",
        "runtime",
        "runtime.server",
        "runtime.ipc",
        "runtime.lifecycle",
        "runtime.handlers.agent",
        "runtime.handlers.ws",
        "runtime.wss",
        "runtime.wss.manager",
        "crawlers.xianyu.ws",
        "crawlers.xianyu.ws.client",
        "crawlers.xianyu.ws.frames",
        "crawlers.xianyu.ws.history",
        "crawlers.xianyu.ws.push",
        "crawlers.xianyu.ws.token",
        "graph",
        "graph.core.context",
        "graph.core.state",
        "graph.core.config",
        "graph.core.graph",
        "graph.workflows.price_compare",
        "graph.workflows.product_monitor",
        "graph.workflows.buyer_reply",
        "runtime.wss.auto_reply",
        "graph.nodes.planner",
        "graph.nodes.search",
        "graph.nodes.finalize",
        "graph.tools.knowledge",
        "graph.tools.xianyu",
        "graph.tools.alibaba",
        "agents.planner",
        "agents.researcher",
        "agents.analyst",
        "config",
        "config.settings",
        "config.models",
        "llm",
        "llm.client",
        "llm.factory",
        "llm.models",
        "llm.embeddings",
        "llm.providers.openai",
        "llm.providers.anthropic",
        "llm.providers.gemini",
        "llm.providers.dashscope_app",
        "llm.providers.deepseek",
        "llm.providers.qwen",
        "knowledge",
        "knowledge.service",
        "knowledge.loader",
        "knowledge.splitter",
        "knowledge.indexer",
        "knowledge.retriever",
        "knowledge.reranker",
        "knowledge.stores.sqlite",
        "tools.web_search",
        "tools.browser",
        "services.product",
        "services.price",
        "services.knowledge",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="sidecar",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
